# Generated by Django 4.1.7 on 2023-03-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
